export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SEARCH_WITH_EXACT_CATEGORY = "SEARCH_WITH_EXACT_CATEGORY";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const GET_PRODUCTS_WITH_PAGINATION = "GET_PRODUCTS_WITH_PAGINATION";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
